#!/usr/bin/env bash
# This outputs bas luck for 4, good luck for 8, Best School for all other
count=0
while [ $count -lt 10 ]; do
	if [ $count -eq 4 ]; then
		echo "bad luck"
	elif [ $count -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((count++))
done
