#!/usr/bin/env bash
# This outputs numbers from 1 to 20, and some other things in the middle
count=0
while [ $count -lt 20 ]; do
	((count++))
	case $count in
		4) echo $count; echo "bad luck from China";;
		9) echo $count; echo "bad luck from Japan";;
		17) echo $count; echo "bad luck from Italy";;
		*) echo $count;;
	esac
done
